addons:
  apt:
    packages:
      - cmake
      - libsfml-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ${TRAVIS_BUILD_DIR} && make
